# Generated by Django 5.2.12 on 2026-03-14 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_page_slug_page_unique_page_slug_per_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='pages.page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['page', 'viewed_at'], name='analytics_p_page_id_778f37_idx'), models.Index(fields=['user', 'viewed_at'], name='analytics_p_user_id_1212d8_idx')],
            },
        ),
    ]
