# Generated by Django 5.2.12 on 2026-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='space',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
