# Generated by Django 5.2.12 on 2026-03-14 20:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_accounts', '0003_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts for this code.')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='E.164 format recommended, e.g. +14155552671', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 9-15 digits, optionally prefixed with +.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Verification')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['status'], name='idx_user_status'),
        ),
        migrations.AddField(
            model_name='phoneverificationtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
