# Generated by Django 5.2.12 on 2026-03-14 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('page_created', 'Page created'), ('page_updated', 'Page updated'), ('page_deleted', 'Page deleted'), ('comment_added', 'Comment added'), ('comment_reply', 'Comment reply'), ('mentioned', 'Mentioned'), ('role_changed', 'Role changed'), ('space_archived', 'Space archived')], max_length=30)),
                ('target_type', models.CharField(help_text='e.g. Page, Comment, Space', max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient_unread')],
            },
        ),
    ]
